apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-project-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: spring-boot-k8s
          image: ilyazhynko/spring-project-k8s:latest
          ports:
            - containerPort: 8080